services:
  polygon_demo:
    container_name: polygon_demo
    extends: .common
    image: polygon_demo
    build:
      target: polygon_demo
    command: ros2 run polygon_base area_node

  .common:
    image: pluginlib
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: base
    runtime: nvidia
    environment:
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDI_DRIVER_CAPABILITIES: compute,video,utility,graphics
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
