services:
  common:
    image: ros2_workshop
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: base
    environment:
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: "1"
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /run/user/1000/gdm/Xauthority:/root/.Xauthority:ro
    command: tail -f /dev/null
